url: BSU-IT-Club.github.io
baseurl: ""

# Site settings
title: BSU IT Club
email: itclub@boisestate.edu
description: "BSU's IT Club"


# Team names, titles and social links
people:
- name: Mason Coler-Dark 
  pic: Mason
  position: Club President
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/mason-coler-dark-4577b9257/
- name: Gabe Tinsley
  pic: Gabe
  position: Education Officer
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/gabrieltinsley/

- name: Tyla Martin
  pic: Tyla
  position: Marketing Officer
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/tylamartin
    - title: instagram
      url: https://www.instagram.com/tylaafe/

- name: Calvin Worst
  pic: Calvin
  position: Cybersecurity Initiatives Officer
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/calvinworst/
  
- name: Gabriel Williams
  pic: 3
  position: IT Ops Team Officer
  social:
  
- name: Evan Bullwinkle
  pic: 3
  position: Technology Officer
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/evan-b-7321b6114/
    - title: github
      url: https://github.com/Mogi83

  
- name: Mayahuel Godinez-Gonzalez
  pic: 3
  position: Relations Officer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #
# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket 
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
